/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/laOD6cSOedZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Gabarito } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link";

export function HeroSection() {
  return (
    (<section
      className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gradient-to-r from-primary to-secondary">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-4xl font-bold tracking-tighter text-primary-foreground sm:text-5xl xl:text-6xl/none">
                Powerful onling meeting setup in an instant
              </h1>
              <p className="max-w-[700px] text-secondary-foreground md:text-xl">
                
              </p>
            </div>
            <div className="w-full max-w-sm space-y-2">
              <div className="flex gap-2">
                {/* <Input type="email" placeholder="Enter your email" className="max-w-lg flex-1" /> */}
                <Link
                href={"/join"}
                  className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-3 py-2 border-[1px] border-solid border-white">
                 join Meeting
                </Link>
                {"   "}
                <Link
                href={"/create"}
                  className="bg-primary text-primary-foreground  bg-gray-300 border-solid border-[1px] border-black text-black hover:bg-gray-300 hover:border-solid hover:border-2 hover:border-black hover:text-black rounded-md px-3 py-2">
                  Create Meeting
                </Link>
              </div>
              <p className="text-xs text-secondary-foreground text-gray-300">
              {/* Powerful onling meeting setup in an instant */}
              </p>
            </div>
          </div>
          <img
            src="/hero-image.jpg"
            width="550"
            height="310"
            alt="Hero"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last" />
        </div>
      </div>
    </section>)
  );
}
