/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3b1fANpLuWN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function JoinMeet() {
  return (
    (<section
      className="w-full py-12 md:py-24 lg:py-32 bg-cover bg-center">
      <div
        className="container px-4 md:px-6 flex flex-col items-center justify-center text-center space-y-6">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Join the Meeting</h1>
          <p className="max-w-[600px] text-muted-foreground md:text-xl">
            Enter the meeting code to join the live session.
          </p>
        </div>
        <div className="w-full max-w-md space-y-2">
          <form className="flex gap-2">
            <Input type="text" placeholder="Enter meeting code" className="flex-1" />
            <Button type="submit">Join</Button>
          </form>
        </div>
      </div>
    </section>)
  );
}
